version: '3'

services:
  web:
    build: './'
    env_file:
      - '.env.override'
    ports:
      - "80:80"
      - "443:443"
  backend:
    image: 'fa4stik/science_track_back'
    command: sh -c "sleep 5 && dotnet ScienceTrack.dll"
    depends_on:
      - postgres
    env_file:
      - '.env.override'
  postgres:
    image: 'postgres:14-alpine'
    env_file:
      - '.env.override'