version: '3'

services:
  web:
    build: './'
    env_file:
      - '.env.override'
    ports:
      - "3000:3000"
  backend:
    image: 'fa4stik/science_track_back'
    command: sh -c "sleep 5 && dotnet ScienceTrack.dll"
    depends_on:
      - postgres
    env_file:
      - '.env.override'
  postgres:
    image: 'postgres'
    ports:
      - "6000:5432"
    env_file:
      - '.env.override'